spring:
  application:
    name: dubbo-spring-boot-consumer

server:
  port: 8080

demo:
  service:
    version: 1.0

dubbo:
  application:
    name: dubbo-spring-boot-consumer
    id: dubbo-spring-boot-consumer
#  protocol:
#    id: dubbo
#    name: dubbo
#    port: 20080
#    threads: 10
  registry:
      id: my-register
      address: 192.168.3.124:2181
      protocol: zookeeper
      client: curator
      timeout: 30000
  consumer:
    client: netty4

#management:
#  server:
#    port: 8081